# -*- coding: utf-8 -*-
"""python_assignment_27_11_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_zd-DnlIz6dEfNDEBAPoAi96ALmaAXL
"""

def is_prime(num):
  if num <= 1:
    return False
  for i in range(2, int(num ** 0.5) + 1):
    if num % i == 0:
      return False
  return True

from random import randint

def check_product():
    num1 = randint(0, 100)
    num2 = randint(0, 100)
    try:
      answer = input(f"Enter the product of {num1} and {num2}: ")
    except:
      print("Only enter a integer")
    if int(answer) == (num1 * num2):
        print(f"The product of {num1} and {num2} is indeed {answer}")
    else:
        print("Wrong answer")
check_product()

# Printing the squares of the even numbers
def print_even_squares(num1, num2):
  for i in range(num1, num2+1):
    print(i**2);

print_even_squares(100,200)

ROOM_CHARGE_PER_DAY = 2000
DOCTOR_FEE = 1500
LAB_TEST_COST = 300
class HospitalBill:
    def __init__(self, days_stayed, num_tests, medicine_charges):
        self.days_stayed = days_stayed
        self.num_tests = num_tests
        self.medicine_charges = medicine_charges

    def calculate_bill(self):
        room_total = ROOM_CHARGE_PER_DAY * self.days_stayed
        lab_test_total = LAB_TEST_COST * self.num_tests

        total_before_discount = (
            room_total +
            DOCTOR_FEE +
            lab_test_total +
            self.medicine_charges
        )

        if total_before_discount > 10000:
            discount = total_before_discount * 0.10
        else:
            discount = 0

        final_bill = total_before_discount - discount
        return total_before_discount, discount, final_bill

patient = HospitalBill(days_stayed=4, num_tests=3, medicine_charges=2400)
total, discount, final = patient.calculate_bill()
print("Total before discount:", total)
print("Discount:", discount)
print("Final bill:", final)