# -*- coding: utf-8 -*-
"""python_assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ibov6WL4zS7ORlYAGJsCxq9k9YX4cyUW
"""

def list_operations():
  l = [14,56,28,97,33]
  print(l)
  l.clear()
  print(l)
  l.extend([44,26,45,78,3,12])
  print(l)
  l.insert(4,265)
  print(l)
  l.remove(26)
  print(l)
  l.pop()
  print(l)
  l.index(78)
  print(l)
  l.append(12)
  print(l)
  l.count(12)
  print()
  l.sort()
  print(l)
  l.reverse()
  print(l)


list_operations()

def tuple_operations():

  names = ("Karthik J", "Megha Lokesh", "Shreya Subramanian")
  try:
    # We cannot modify a tuple in python.
    # 1. We use Tuple to store values that we know can not change.
    # 2. We can use immutable data types as a key in dictionaries, we can use tuple as a key in python dict.
    names[1] = "Angelina Jolie"
  except Exception as e:
    print(e)

tuple_operations()

def set_operations():

  s = {1,4,5,5,6,7,8,9}
  # The Set is used to store only unique values in Python, duplicate values are discarded.
  print(s) # {1,4,5,6,7,8,9} The order can change in Set

set_operations()

def dict_operations():

  d = {
      "name":"Karthik J",
      "age":55,
      "city":"Bengaluru"
  }
  print(d)
  d["age"] = 88
  print(d)
  d["email"]="karthikrdy150502@gmail.com"
  print(d)

dict_operations()

def check_age(age):

  if age >= 18:
    print("You are eligible to vote")
  else:
    print("You are not eligible to vote")

check_age(15)
check_age(30)

def check_grade(marks):

  if marks >= 90:
    return "A"
  elif marks >= 75:
    return "B"
  elif marks >= 50:
    return "C"
  else:
    return "FAIL"

print(check_grade(74))
print(check_grade(22))
print(check_grade(99))
print(check_grade(89))

def check_even_positive_number(num):
  if num > 0:
    if num%2 == 0:
      print("Number is positive and even.")
    else:
      print("Number is positive and odd.")
  elif num < 0:
     if num%2 == 0:
      print("Number is negative and even.")
     else:
      print("Number is negative and odd.")
  else:
    print("the number is 0.")

check_even_positive_number(2)
check_even_positive_number(15)
check_even_positive_number(0)
check_even_positive_number(-2)
check_even_positive_number(-7)

# Numpy operations
import numpy as np
import pandas as pd

def numpy_operations():

  # 1. Scalar
  print("Scalar using np.array(5):")
  scalar = np.array(5)
  print(scalar, "\n")

  # 2. 1D array (manual)
  print("1D array with values 1 to 5 (manual):")
  arr_1d_manual = np.array([1, 2, 3, 4, 5])
  print(arr_1d_manual, "\n")

  # 3. 1D array (using arange)
  print("1D array with values 1 to 5 (using np.arange):")
  arr_1d = np.arange(1, 6)
  print(arr_1d, "\n")

  # 4. 2D array (2x3) – values 10 to 60 step 10
  print("2D array (2x3) with values 10 to 60:")
  arr_2d = np.arange(10, 70, 10).reshape(2, 3)
  print(arr_2d, "\n")

  # 5. Random 4x4 integer array
  print("Random 4x4 array with values 0 to 100:")
  rand_arr = np.random.randint(0, 101, size=(4, 4))
  print(rand_arr, "\n")

  # 6. 3x3 array → DataFrame
  print("Pandas DataFrame (from 3x3 numpy array):")
  arr = np.arange(1, 10).reshape(3, 3)
  df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
  print(df)


numpy_operations()

import pandas as pd
import numpy as np

def pandas_operations():
  # 1. Create a small DataFrame with 10 rows manually
  print("Original DataFrame:\n")

  data = {
      'Name': ['Karthik', 'Nakul', 'Rohit', 'Arun', 'Sam', 'Riya', 'Karthik', 'Nakul', 'John', 'Meera'],
      'Age': [23, 25, 22, 30, 28, 26, 23, 25, 29, 24],
      'City': ['Bangalore', 'Delhi', 'Mumbai', 'Chennai', 'Delhi', 'Pune', 'Bangalore', 'Delhi', 'Hyderabad', 'Chennai'],
      'Salary': [50000, 60000, np.nan, 55000, 52000, 61000, 50000, 60000, 58000, np.nan]   # includes missing values
  }

  df = pd.DataFrame(data)
  print(df, "\n")


  # 2. Use .info() and .describe()
  print("DataFrame info():")
  print(df.info(), "\n")

  print("DataFrame describe():")
  print(df.describe(), "\n")


  # 3. Select 'Name' and 'City' columns
  print("Selecting 'Name' and 'City' columns:\n")
  print(df[['Name', 'City']], "\n")


  # 4. Drop 'City' column
  print("DataFrame after dropping 'City' column:\n")
  df_dropped = df.drop(columns=['City'])
  print(df_dropped, "\n")


  # 5. Fill missing values in 'Salary' with mean
  print("Filling missing Salary values with mean:\n")
  mean_salary = df_dropped['Salary'].mean()
  df_filled = df_dropped.fillna({'Salary': mean_salary})
  print(df_filled, "\n")


  # 6. Remove duplicate rows
  print("Removing duplicate rows:\n")
  df_unique = df_filled.drop_duplicates()
  print(df_unique)


pandas_operations()